In [453]:
from sklearn import datasets # used for load iris dataset
from sklearn.model_selection import train_test_split # used for split our dataset train-test (70% - 30%)
from sklearn.metrics import accuracy_score # used for get accuracy
import numpy as np # used for array operations: shape,concatenate,expand_dims,square-root and substraction

In [454]:
dataset = datasets.load_iris() # load iris dataset

In [455]:
dataset # let's look the dataset

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [456]:
dataset.keys() # let's look keys of the dataset to decide what columns i need

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [457]:
# After examine dataset and dataset keys , i am taking needed columns 
X = dataset.data
y = dataset.target
features = dataset.feature_names
targets = dataset.target_names

In [458]:
# I'm looking my related columns
def giveInfo(X,y):
  print(f"Our feature values:{X}",
      f"\nOur Target values:{y}")
giveInfo(X,y)

Our feature values:[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.

In [459]:
# I should merge two column -> (our feature values and target values) For that target values array dimension is 1 but feature values dims are 2 . So i should expand dims to target_values
y_2d = np.expand_dims(y,axis=1) # convert y to 2dimension array.
X = np.concatenate((X,y_2d),axis=1)
giveInfo(X,y) # I check new feature values.

Our feature values:[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0

In [460]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=78) #I split our data %70 train , 30% test


In [461]:
# Let's chek shapes
print("Shape X:",X.shape,
      f"\n30% : {X.shape[0]*0.3}",
      "\n\nShape X_train:",X_train.shape,
      "\nShape X_test:",X_test.shape,
      "\nShape y",y.shape,
      "\nShape y_train:",y_train.shape,
      "\nShape y_test:",y_test.shape)

Shape X: (150, 5) 
30% : 45.0 

Shape X_train: (105, 5) 
Shape X_test: (45, 5) 
Shape y (150,) 
Shape y_train: (105,) 
Shape y_test: (45,)


In [462]:
# Let's check our features,targets and their values 
print("Points' feature names:",features,
      "\nFirst point's feature values:",X_train[0],
      "\nFirst point's target value:",y_train[0],
      "\nFirst point's target name:",targets[y_train[0]])

Points' feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 
First point's feature values: [4.8 3.  1.4 0.3 0. ] 
First point's target value: 0 
First point's target name: setosa


In [463]:
# Everything is fine until now. I will use euclidean distance formula to calculate distances between points
def euclideanDistance(points1,points2):
  '''
  Formula : dist = square root ( subtracting of two point coordinate ^2).
  Input : points1 : coordinates of the point is in our dataset.
          points2 : coordinates of our point will be predicted. 
  Output : return distance is between points1 and points2
  '''
  distance = 0.0
  for i in range(len(points1) - 1 ): # we should substrac 1 . cuz last value is target value
    distance += (points1[i] - points2[i])**2 # (x1_i-x2_i)^2 
  dist = np.sqrt(distance)
  return dist

In [464]:
# I calculate distances and points then return all distances and points as a list.
def getPointsAndDistances(y,y_hat):
  '''
  Inputs : y -> our dataset 
           y_hat -> it's point will be predicted belong which class.
  Output : return all distances and with related points. 
  '''
  distances = list() # to store our distances
  for point in y:
    distance = euclideanDistance(point,y_hat) #calculate euc.distance 
    distances.append((point,distance)) #save points and the distance
  return distances
# I find nearest neighbors depending the distances list values
def findNearestNeighbors(pointsAndDistances,all_k):
  '''
  Inputs : pointsAndDistances -> All points and calculated distances with points values
           all_k -> Neighbors count
  Output : Return nearest neighbors values
  '''
  neighbors = list()
  pointsAndDistances.sort(key = lambda d : d[1]) #sort list by second element(second element is distances) .
  for k in range(all_k): #show our neighbors
    neighbors.append(pointsAndDistances[k][0]) # I added all neighbors ,and also target value of the neighbor.
  return neighbors

In [465]:
# for prediction ..
def toPredict(class_names,neighbors):
  '''
  Inputs : class_names : all class values
           neighbors : all neighbors

  Output : return max count of neighbors class(target values)
  '''
  ## Initialize count of all class values
  class_counts  = dict.fromkeys((class_names),0)

  #Initialize prediction point's class counts.
  prediction_class_counts = class_counts
  #Let's calculate class count of prediction point
  for c in neighbors: # Choose neighbors
    if c[-1] in prediction_class_counts.keys(): # If neighbors class exist prediction class. Then add +1.
      prediction_class_counts[c[-1]] +=1 
  most = max(prediction_class_counts.values()) # Find maximum count of classes. 
  prediction = list(prediction_class_counts.values()).index(most) # Find class that belong which class.
  
  return prediction


In [466]:
# All functions is prepared to use . Define knn and then run.
def knn(train,test,num_neighbors):
  '''
  Inputs: train -> train examples
          test -> test examples : points will be predicted belong which class
          num_Neighbors : count of neighbors
  Output: return all predictions of test set
  '''
  classes = dataset.target # all class values : in our dataset are [0,1,2]
  predictions = list() # to store predictions
  for prediction in test: # for test dataset , run all points
    distances = getPointsAndDistances(train,prediction) # calculate distance
    neighbors = findNearestNeighbors(distances,num_neighbors) # find nearest neighbors
    y_hat = toPredict(classes,neighbors) # to predict
    predictions.append(y_hat) # store prediction value in prediction list
  return predictions

In [467]:
# Show results 
def predictAndFindAccuracy(k):
  '''
  k is count of neighbors.
  '''
  predictions = knn(X_train,X_test,k) # run knn function
  print(f"knn is running for k = {k}") 
  wrong_prediction_count = 0
  for i in range(len(predictions)): # show all predictions
    if predictions[i] != y_test[i]:
      print(f"!!! {i}.prediction is WRONG -> Prediction:{predictions[i]},Real:{y_test[i]}")
      wrong_prediction_count += 1
    #else:
     # print(f"Prediction:{predictions[i]},Real:{y_test[i]}")
  scores = accuracy_score(y_test,predictions) # calculate accuracy using with scikitlearn lib.
  print(f"k = {k} \t\t\t Wrong Prediction Count : {wrong_prediction_count} \nAccuracy: {scores:.4f} \t Total prediction:{len(predictions)}\n\n\t\t********\n")
  return scores
predictAndFindAccuracy(1)
predictAndFindAccuracy(3)
predictAndFindAccuracy(5)
predictAndFindAccuracy(y_test.shape[0])

#for i in range(y_test.shape[0]):
# predictAndFindAccuracy(i)

'''
Observations:
If k is too small accuracy is low because of overfitting. Model is memorize.
If k is too large accuracy is decrease again because our model is too simple.
'''

knn is running for k = 1
!!! 11.prediction is WRONG -> Prediction:2,Real:1
!!! 21.prediction is WRONG -> Prediction:2,Real:1
k = 1 			 Wrong Prediction Count : 2 
Accuracy: 0.9556 	 Total prediction:45

		********

knn is running for k = 3
!!! 11.prediction is WRONG -> Prediction:2,Real:1
!!! 21.prediction is WRONG -> Prediction:2,Real:1
k = 3 			 Wrong Prediction Count : 2 
Accuracy: 0.9556 	 Total prediction:45

		********

knn is running for k = 5
!!! 21.prediction is WRONG -> Prediction:2,Real:1
k = 5 			 Wrong Prediction Count : 1 
Accuracy: 0.9778 	 Total prediction:45

		********

knn is running for k = 45
!!! 3.prediction is WRONG -> Prediction:2,Real:1
!!! 11.prediction is WRONG -> Prediction:2,Real:1
!!! 21.prediction is WRONG -> Prediction:2,Real:1
k = 45 			 Wrong Prediction Count : 3 
Accuracy: 0.9333 	 Total prediction:45

		********



'\nObservations:\nIf k is too small accuracy is low because of overfitting. Model is memorize.\nIf k is too large accuracy is decrease again because our model is too simple.\n'